version: "2"
services:
    api:
        build:
            context: "./server"
            dockerfile: "Dockerfile"

        container_name: "api"
        restart: always
        volumes: 
            -   "./server/src:/server/src"
        depends_on: 
            - database
        ports:
        - "${NODE_PORT}:${NODE_PORT}"
        env_file: 
        - ".env"

    database:
        build: ./database
        ports: 
            - "8081:8081"
        environment: 
            - MYSQL_ROOT_PASSWORD=joakimbrandt
            - MYSQL_DATABASE=joakimbrandt